// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tip': string;
  'tip-wrapper': string;
  'tipWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
