import { getModelForClass, prop } from "@typegoose/typegoose";
import mongoose from "mongoose";
import NotificationPreference from "./NotificationPreference";
import { IStudent } from "./Students";

export interface IParent {
  _id?: mongoose.Types.ObjectId;
  firebaseUID: string; // Should be autogenerated by client-side firebase.
  name: string;
  email: string;
  timezone: string;
  phone: string;
  pronouns: string;
  avatar: string; // Assumed to be a URL
  notificationPreference: NotificationPreference;
  students: IStudent[];
}

export class Parent implements IParent {
  public _id: mongoose.Types.ObjectId;

  @prop({ required: true, unique: true })
  public firebaseUID: string;

  @prop({ required: true })
  public name: string;

  @prop({ required: true, unique: true })
  public email: string;

  @prop({ required: true })
  public timezone: string;

  @prop({ required: true })
  public phone: string;

  @prop({ required: true })
  public pronouns: string;

  @prop({ required: true })
  public notificationPreference: NotificationPreference;

  @prop({ required: true })
  public avatar: string;

  @prop({
    required: true,
    validate: {
      validator: (v) => v.length >= 1,
      message: "Parent must specific at least one student.",
    },
  })
  public students: IStudent[];
}

const ParentModel = getModelForClass(Parent);

export default ParentModel;
